version: "3.7"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
        container_name: elasticsearch
        restart: always
        logging:
          driver: "json-file"
          options:
           max-size: "100m"
        environment:
            - TZ=Asia/Ho_Chi_Minh
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
            - discovery.type=single-node
        networks:
            - local-network
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data
    kibana:
        image: docker.elastic.co/kibana/kibana:7.17.0
        container_name: kibana
        restart: always
        depends_on:
            - elasticsearch
        networks:
            - local-network
        ports:
            - 5601:5601

networks:
    local-network:
      external: true