version: '3'

services:
  master:
    image: citusdata/citus:12.1
    container_name: citus_master
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - citus_master_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_connections=200"]

  worker1:
    image: citusdata/citus:12.1
    container_name: citus_worker1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - citus_worker1_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_connections=200"]

  worker2:
    image: citusdata/citus:12.1
    container_name: citus_worker2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - citus_worker2_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_connections=200"]

volumes:
  citus_master_data:
  citus_worker1_data:
  citus_worker2_data: