version: '3'
services:
  # postgres:
  #     image: postgres:${SOFTWARE_VERSION_TAG}
  #     restart: always
  #     #command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
  #     environment:
  #       POSTGRES_DB: postgres
  #       POSTGRES_USER: postgres
  #       POSTGRES_PASSWORD: ${SOFTWARE_PASSWORD}
  #       PGDATA: /var/lib/postgresql/data
  #     volumes:
  #     - ./data:/var/lib/postgresql/data
  #     ports:
  #     - '5432:5432'
  pgadmin4:
      image: elestio/pgadmin:latest
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@gmail.com
        PGADMIN_DEFAULT_PASSWORD: 123456aA@
        PGADMIN_LISTEN_PORT: 8989
      ports:
      - "8989:8989"
      volumes:
      - ./servers.json:/pgadmin4/servers.json
