services:
  paste:
    image: danielszabo99/microbin
    container_name: microbin
    restart: always
    environment:
     - MICROBIN_PRIVATE=false
     - MICROBIN_PUBLIC_PATH=<your-domain>
     - MICROBIN_QR=true
     - MICROBIN_HIGHLIGHTSYNTAX=true
     - MICROBIN_ADMIN_USERNAME=admin
     - MICROBIN_ADMIN_PASSWORD=123456aA@
     - MICROBIN_ENCRYPTION_CLIENT_SIDE=false
     - MICROBIN_ENCRYPTION_SERVER_SIDE=true
     - MICROBIN_TITLE=Microbin
     - MICROBIN_QR=True
     - MICROBIN_HIDE_FOOTER=True
     - MICROBIN_WIDE=true
    ports:
     - "8065:8080"
    volumes:
     - ./docker/microbin:/my/microbin
     - ./docker/microbin/data:/app/pasta_data