version: "3"

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123456aA@
      MYSQL_DATABASE: mRemoteNG
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456aA@
    ports:
      - "6033:3306"
    volumes:
      - G:/My Drive/Devops/mRemoteNG/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  dbdata:
