version: "3.7"

services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        # deploy:
        #     resources:
        #         limits:
        #           cpus: '4.0'
        #           memory: 8G
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - TZ=Asia/Ho_Chi_Minh
        # networks:
        #     - local-network
        ports:
            - 5433:5432
        volumes:
            - data-postgres:/var/lib/postgresql/data
volumes:
    data-postgres:
# networks:
#     local-network:
#       external: true